### PR TITLE
Mixed Models Fixes

### PR DESCRIPTION
**Pull request by FBartos**
fixes: jasp-stats/jasp-test-release#1209
fixes: jasp-stats/jasp-test-release#1454
fixes: jasp-stats/jasp-test-release#1403

### CODE REVIEW

**Comment by vandenman** [comment]
did you intend to assign a reviewer?

**Comment by FBartos** [comment]
yes, that sounds like a sensible idea. Would you have time to review it?

**Comment by vandenman** [comment]
Not this week probably, but I can take a look at the beginning of next week.

**Comment by FBartos** [comment]
ok, thanks

**Comment by FBartos** [comment]
(only added a simple fix - renaming table based on qml input - for bug that I missed before)

**Review by vandenman — APPROVED** [review]

**Pull request merged**
