### PR TITLE
Add dependencies and configuration files

### PR DESCRIPTION
**Pull request by TimKDJ**

### CODE REVIEW

**Comment by FBartos** [comment]
I'm not sure whether we were using a specific version of emmeans and afex, but we might have moved forward already

**Comment by TimKDJ** [comment]
@FransMeerhoff do you know if we're on specific versions of these packages?

**Comment by FransMeerhoff** [comment]
@TimKDJ We use the following versions both from CRAN :
afex version 0.28-0 last update on 21-09-2020 see https://github.com/jasp-stats/jasp-required-files/commit/8187dc8b5b8556fbd18248e51ebcd499b5efc97b
emmeans version 1.4.7 last update 17-06-2020 https://github.com/jasp-stats/jasp-required-files/commit/696afc9284f091031e8a8facf789c13e9e25cce0

**Comment by TimKDJ** [comment]
Do you happen to know if we use these specific versions because older ones are not sufficient?

**Comment by FransMeerhoff** [comment]
@TimKDJ @FBartos : Do not know exactly what goes wrong and where:
Reminder for František on 18-09-2020 : " Hi Frans, could you update the afex  package (from CRAN) and  ... "
That was the latest update from me. Did I miss another request?

**Comment by FBartos** [comment]
@TimKDJ yes, that looks like the versions of the packages that are used while I don't get error messages (or only the different figures errors) in the unit tests

**Pull request merged**
