### PR TITLE
Release fixes

### PR DESCRIPTION
**Pull request by FBartos**
fixes: https://github.com/jasp-stats/jasp-test-release/issues/2806
fixes: https://github.com/jasp-stats/jasp-test-release/issues/2807
fixes: https://github.com/jasp-stats/jasp-test-release/issues/2810
fixes: https://github.com/jasp-stats/jasp-test-release/issues/2811

### CODE REVIEW

**Comment by boutinb** [comment]
The https://github.com/jasp-stats/jasp-test-release/issues/2807 still fails

**Comment by FBartos** [comment]
> The [jasp-stats/jasp-test-release#2807](https://github.com/jasp-stats/jasp-test-release/issues/2807) still fails

well, you cannot untick the intercept, so you cannot reproduce the error in other way than loading the data set :)

**Comment by RensDofferhoff** [comment]
@boutinb @FBartos should I just alter the datalib files by checking intercept?

**Comment by FBartos** [comment]
I think the data lib files do have checked intercept -- this error occurred once the intercept was unchecked

**Comment by boutinb** [comment]
> think the data lib files do have checked intercept -- this error occurred once the intercept was unchecked

I'm not sure to understand: if I load a csv file, I add the Bayesian Linear Mixed Model, I set a dependent variable, a fixed effects and a Random effect, and then unset the 'Include intercept': i get this error.
If I do that with the Classical Linear Mixed Model, I don't get any error.
In 0.19.1, we have the same problem.
If in the Bayesian version, the Intercept must be always set, then let's disable it.

**Comment by FBartos** [comment]
> I'm not sure to understand: if I load a csv file, I add the Bayesian Linear Mixed Model, I set a dependent variable, a fixed effects and a Random effect, and then unset the 'Include intercept': i get this error.
> If I do that with the Classical Linear Mixed Model, I don't get any error.
> In 0.19.1, we have the same problem.
> If in the Bayesian version, the Intercept must be always set, then let's disable it.

Yes, indeed, that's what this PR does
https://github.com/jasp-stats/jaspMixedModels/pull/193/files#diff-8d00a9863284d8353ec247264278f6a683e47ede754168d1eeec45cab4150ea9R66-R69
and
https://github.com/jasp-stats/jaspMixedModels/pull/193/files#diff-b24bbd7477efa6362f979b53402ed5a9a0a9939bd5f3271f0e0f03f5731a5b8aR51-R54

**Comment by boutinb** [comment]
Ok, then  we can merge this, @RensDofferhoff ?

**Review by RensDofferhoff — APPROVED** [review]
Yes

**Pull request merged**
